# See the list of lints at https://rust-lang.github.io/rustfmt/?version=v1.4.38&search=
# binop_separator = "Back"
edition = "2021"
# format_code_in_doc_comments = true
# format_strings = true
# group_imports = "StdExternalCrate"
hard_tabs = false
# imports_granularity = "Module"
# normalize_comments = true
# normalize_doc_attributes = true
# reorder_impl_items = true
reorder_imports = true
reorder_modules = true
tab_spaces = 2
# trailing_comma = "Never"
# trailing_semicolon = true
# unstable_features = true
use_try_shorthand = true
# wrap_comments = true
